FROM bitnami/spark:3.5.0

USER root

# Install pip and required packages
RUN apt-get update && \
    apt-get install -y python3-pip ca-certificates curl gnupg && \
    update-ca-certificates && \
    pip3 install --no-cache-dir \
      --trusted-host pypi.org \
      --trusted-host pypi.python.org \
      --trusted-host files.pythonhosted.org \
      pytest==7.0.0 \
      pymongo==3.12.0 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy requirements file
COPY requirements.txt /tmp/requirements.txt

# Install dependencies from the requirements.txt file
RUN pip install --no-cache-dir --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org -r /tmp/requirements.txt

# Set the working directory to /tests where the test scripts should be located
WORKDIR /tests

# Make sure Python can find Spark and Py4J
ENV PYTHONPATH="/opt/bitnami/spark/python:/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip:${PYTHONPATH}"

# Switch back to a non-root user to ensure safe execution
USER 1001

# Default command to run the tests with additional options for more readable output
CMD ["pytest", "-v", "--disable-warnings", "--maxfail=5"]
