version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./tests:/tests
      - ./jars:/extra-jars  # Ensure JARs are mounted here as well
    depends_on:
      - mysql
      - mongodb
    command: ["pytest", "/tests"]  # Ensure pytest runs automatically when the container starts
    healthcheck:
      test: ["CMD", "pytest", "--maxfail=1", "--disable-warnings", "/tests"]  # Check if tests pass
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  spark:
    build:
      context: .
      dockerfile: Dockerfile  # Use Dockerfile for building the custom image
    container_name: spark
    environment:
      - SPARK_MODE=master
    volumes:
      - ./app:/app
      - ./jars:/extra-jars
      - ./sql:/sql  # Ensure the path is correctly mounted
    depends_on:
      - mysql
      - mongodb
      - test  # Ensure `test` service has completed before spark starts
    # Note: Docker will only start this service once the test container is healthy

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: northwind
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d  # Mount SQL scripts here for initialization

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
